services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: saaskip-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5455:5432'
    volumes:
      - saaskip-postgres-data:/var/lib/postgresql/data
      - ./docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    networks:
      - saaskip-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  saaskip-network:
    name: saaskip-network
    driver: bridge

volumes:
  saaskip-postgres-data:
    name: saaskip-postgres-data
    driver: local
