const ignore = [
  '.agents/**',
  '.next/**',
  '.ops/**',
  '.stryker-tmp/**',
  '.temp/**',
  '.vitepress/**',
  '.vscode/**',
  '.windsurf/**',
  'commitlint.config.mjs',
  'coverage/**',
  'docker/**',
  'docs/**',
  'logs/**',
  'next-env.d.ts',
  'node_modules/**',
  'playwright-report/**',
  'playwright.config.mjs',
  'reports/**',
  'src/ui/components/ui/**',
  'stryker.config.mjs',
  'test-results/**',
];

export default ignore;
