sonar.projectKey=oclio_nexaas
sonar.organization=oclio

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/__tests__/**,**/*.spec.ts,**/*.spec.tsx,**/__e2e__/**,**/*.e2e-spec.ts
sonar.coverage.exclusions=**/*.d.ts,src/**/__e2e__/**,src/**/__tests__/**,src/**/types.ts,src/**/types/**,src/core/errors/codes.ts,src/core/errors/index.ts,src/core/helpers/index.ts,src/core/i18n/navigation.ts,src/core/i18n/request.ts,src/core/i18n/routing.ts,src/core/observability/axiom/client.ts,src/core/observability/axiom/server.ts,src/core/security/headers.ts,src/ui/components/shadcn/**,src/ui/icons/index.ts
sonar.cpd.exclusions=**/__e2e__/**,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
